[project]
name = "sound-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "cffi==1.17.1",
    "ffmpeg-python==0.2.0",
    "future==1.0.0",
    "gevent==24.11.1",
    "greenlet==3.1.1",
    "humanize==4.12.2",
    "numpy==2.2.4",
    "packaging==24.2",
    "pycparser==2.22",
    "scipy==1.15.2",
    "setuptools==78.1.0",
    "soundfile==0.13.1",
    "tqdm==4.67.1",
    "zope-event==5.0",
    "zope-interface==7.2",
]
